[common]
platform = espressif32
framework = arduino
monitor_speed = 115200
build_flags =
    -DCORE_DEBUG_LEVEL=3

[env:sensor_node]
extends = common
board = esp32-c3-devkitm-1
build_src_filter = +<common/> +<sensor_node/>

[env:central]
extends = common
board = esp32dev
build_src_filter = +<common/> +<central/>
lib_deps =
    knolleary/PubSubClient
